##
## EPITECH PROJECT, 2020
## arcade
## File description:
## arcade: games/Makefile
##

all:
		@make -C pacman/ --no-print-directory
		@make -C nibbler/ --no-print-directory

fclean:
		@make -C pacman/ fclean --no-print-directory
		@make -C nibbler/ fclean --no-print-directory

re:		fclean all
